theme: jekyll-theme-minimal
title: Rami Masri 
description: <img align="center" width="207.34" height="250" src="Rami_Portrait-4.jpg"><br><br> I am a postdoctoral fellow at Simula Research Laboratory supervised by Prof. <a href = "https://www.simula.no/people/meg">Marie Rognes</a>. I obtained my Ph.D. from the Department of Computational and Applied Mathematics (CAAM) at Rice University supervised by Prof. <a href="http://compm.rice.edu/people-2/beatrice-riviere/">Beatrice Riviere</a>.
 Here is my <a href="https://scholar.google.com/citations?user=soPrbk0AAAAJ&hl=en&oi=ao"> Google scholar<a/>.  

